const $Html = document.querySelector(".content-html");

const htmlText = [
	"&lt;!DOCTYPE html&gt;",
	"&lt;html&gt;",
	"&lt;head&gt;",
	"&lt;meta&gt;",
	"&lt;title&gt;",
	"&lt;link&gt;",
	"&lt;body&gt;",
	"&lt;header&gt;",
	"&lt;main&gt;",
	"&lt;footer&gt;",
	"&lt;aside&gt;",
	"&lt;div&gt;",
	"&lt;h1 - h6&gt;",
	"&lt;p&gt;",
	"&lt;i&gt; / &lt;em&gt;",
	"&lt;b&gt; / &lt;strong&gt;",
	"&lt;ul&gt;",
	"&lt;ol&gt;",
	"&lt;li&gt;",
	"&lt;a&gt;",
	"&lt;br&gt;",
	"&lt;hr&gt;",
	"&lt;img&gt;",
	"&lt;script&gt;",
	"&lt;!-- --&gt;",
	"&lt;style&gt;",
	"&lt;nav&gt;",
	"&lt;section&gt;",
	"&lt;article&gt;",
	"&lt;span&gt;",
	"&lt;dl&gt;",
	"&lt;dt&gt;",
	"&lt;dd&gt;",
	"&lt;table&gt;",
	"&lt;thead&gt;",
	"&lt;tfoot&gt;",
	"&lt;tbody&gt;",
	"&lt;th&gt;",
	"&lt;tr&gt;",
	"&lt;td&gt;",
	"&lt;form&gt;",
	"&lt;input&gt;",
	"&lt;button&gt;",
	"&lt;label&gt;",
	"&lt;fieldset&gt;",
	"&lt;legend&gt;",
];
const htmlId = [
	"doctype-tag",
	"html-tag",
	"head-tag",
	"meta-tag",
	"title-tag",
	"link-tag",
	"body-tag",
	"header-tag",
	"main-tag",
	"footer-tag",
	"aside-tag",
	"div-tag",
	"h1-h6-tag",
	"p-tag",
	"i-tag",
	"b-tag",
	"ul-tag",
	"ol-tag",
	"li-tag",
	"a-tag",
	"br-tag",
	"hr-tag",
	"img-tag",
	"script-tag",
	"comment-tag",
	"style-tag",
	"nav-tag",
	"section-tag",
	"article-tag",
	"span-tag",
	"dl-tag",
	"dt-tag",
	"dd-tag",
	"table-tag",
	"thead-tag",
	"tfoot-tag",
	"tbody-tag",
	"th-tag",
	"tr-tag",
	"td-tag",
	"form-tag",
	"input-tag",
	"button-tag",
	"label-tag",
	"fieldset-tag",
	"legend-tag",
];

for (let i = 0; i < htmlText.length; i++) {
	let div = document.createElement("div");
	div.innerHTML = htmlText[i];
	div.className = "content-html__item";
	div.id = htmlId[i];
	$Html.appendChild(div);
}
